# Generated by Django 4.0.4 on 2022-04-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('notas', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
